-- 주간 일소진 상승 프로모션
--   주(월~일)의 일평균 광고비가 직전 주 일평균 + 상승 목표 이상이면 달성 (개인·팀 각각)
--   광고비: 네이버 유상실적(VAT 별도, 급여 실적과 같은 기준) + 대상에 따라 메타. 바이럴은 넣지 않음
--   목표·기간은 대표·팀장이 언제든 고치고, 바꾼 내용은 이력으로 남김. 마감하면 그때 숫자를 결과로 보관
create table public.promo_weeks (
  id             uuid primary key default gen_random_uuid(),
  title          text,
  base_start     date not null,
  base_end       date not null,
  week_start     date not null,
  week_end       date not null,
  team_increment bigint not null default 0 check (team_increment >= 0),
  reward_personal text not null default '다음 주 중 사용',
  reward_team     text not null default '다음 주 금요일 17시 퇴근 (팀 전원)',
  reward_personal_hours numeric(3,1) not null default 1 check (reward_personal_hours >= 0),
  reward_team_hours     numeric(3,1) not null default 2 check (reward_team_hours >= 0),
  memo           text,
  closed_at      timestamptz,
  results        jsonb,
  created_by     uuid references public.staff(id) on delete set null default public.my_staff_id(),
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  check (base_start <= base_end and base_end < week_start and week_start <= week_end),
  unique (week_start)
);
comment on table public.promo_weeks is '주간 일소진 상승 프로모션 주차';

create table public.promo_targets (
  week_id   uuid not null references public.promo_weeks(id) on delete cascade,
  staff_id  uuid not null references public.staff(id) on delete cascade,
  increment bigint not null default 0 check (increment >= 0),
  scope     text not null default 'naver_meta' check (scope in ('naver','naver_meta')),
  in_team   boolean not null default true,
  primary key (week_id, staff_id)
);
comment on column public.promo_targets.scope is 'naver=네이버만(예: 영업AE, 인계건 제외), naver_meta=네이버+메타';

create table public.promo_history (
  id         bigint generated by default as identity primary key,
  week_id    uuid not null references public.promo_weeks(id) on delete cascade,
  changed_by uuid references public.staff(id) on delete set null,
  changed_at timestamptz not null default now(),
  what       text not null,
  before     jsonb,
  after      jsonb
);

create or replace function public.promo_weeks_touch() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  if tg_op = 'UPDATE' then
    new.updated_at := now();
    if (new.closed_at, new.results) is distinct from (old.closed_at, old.results)
       and coalesce(current_setting('app.promo_close', true), '') <> 'on' then
      raise exception '마감·마감 풀기는 마감 버튼으로만 할 수 있습니다';
    end if;
    if old.closed_at is not null and new.closed_at is not null and new.results is not distinct from old.results
       and (new.base_start, new.base_end, new.week_start, new.week_end, new.team_increment) is distinct from
           (old.base_start, old.base_end, old.week_start, old.week_end, old.team_increment) then
      raise exception '마감된 주차는 마감을 풀어야 고칠 수 있습니다';
    end if;
    if (old.base_start, old.base_end, old.week_start, old.week_end, old.team_increment, old.reward_personal, old.reward_team, old.title, old.reward_personal_hours, old.reward_team_hours) is distinct from
       (new.base_start, new.base_end, new.week_start, new.week_end, new.team_increment, new.reward_personal, new.reward_team, new.title, new.reward_personal_hours, new.reward_team_hours) then
      insert into public.promo_history(week_id, changed_by, what, before, after)
      values (new.id, public.my_staff_id(), '주차 설정',
        jsonb_build_object('base', old.base_start || '~' || old.base_end, 'week', old.week_start || '~' || old.week_end, 'team', old.team_increment, 'title', old.title, 'hours', old.reward_personal_hours || '/' || old.reward_team_hours),
        jsonb_build_object('base', new.base_start || '~' || new.base_end, 'week', new.week_start || '~' || new.week_end, 'team', new.team_increment, 'title', new.title, 'hours', new.reward_personal_hours || '/' || new.reward_team_hours));
    end if;
  end if;
  return new;
end $$;
create trigger promo_weeks_touch before update on public.promo_weeks for each row execute function public.promo_weeks_touch();

create or replace function public.promo_targets_log() returns trigger
language plpgsql security definer set search_path = public as $$
declare w uuid := coalesce(new.week_id, old.week_id); nm text;
begin
  if exists (select 1 from public.promo_weeks where id = w and closed_at is not null) then
    raise exception '마감된 주차는 마감을 풀어야 고칠 수 있습니다';
  end if;
  select name into nm from public.staff where id = coalesce(new.staff_id, old.staff_id);
  if tg_op = 'UPDATE' and (old.increment, old.scope, old.in_team) is not distinct from (new.increment, new.scope, new.in_team) then
    return new;
  end if;
  -- 주차를 처음 만들 때 넣는 목표는 이력에 남기지 않음 (만든 직후 1분 안)
  if tg_op = 'INSERT' and exists (select 1 from public.promo_weeks where id = w and created_at > now() - interval '1 minute') then
    return new;
  end if;
  insert into public.promo_history(week_id, changed_by, what, before, after)
  values (w, public.my_staff_id(), nm || ' 목표',
    case when tg_op <> 'INSERT' then jsonb_build_object('increment', old.increment, 'scope', old.scope, 'in_team', old.in_team) end,
    case when tg_op <> 'DELETE' then jsonb_build_object('increment', new.increment, 'scope', new.scope, 'in_team', new.in_team) end);
  return coalesce(new, old);
end $$;
create trigger promo_targets_log before insert or update or delete on public.promo_targets for each row execute function public.promo_targets_log();

-- 마감: 화면에서 계산한 결과를 그대로 보관 / 마감 풀기
create or replace function public.promo_close(p_week uuid, p_results jsonb) returns void
language plpgsql security definer set search_path = public as $$
begin
  if not public.is_manager() then raise exception '대표·팀장만 마감할 수 있습니다'; end if;
  perform set_config('app.promo_close', 'on', true);
  update public.promo_weeks set closed_at = now(), results = p_results where id = p_week and closed_at is null;
  if not found then raise exception '이미 마감했거나 없는 주차입니다'; end if;
  insert into public.promo_history(week_id, changed_by, what, after) values (p_week, public.my_staff_id(), '마감', p_results);
end $$;
create or replace function public.promo_reopen(p_week uuid) returns void
language plpgsql security definer set search_path = public as $$
begin
  if not public.is_manager() then raise exception '대표·팀장만 마감을 풀 수 있습니다'; end if;
  perform set_config('app.promo_close', 'on', true);
  update public.promo_weeks set closed_at = null, results = null where id = p_week and closed_at is not null;
  insert into public.promo_history(week_id, changed_by, what) values (p_week, public.my_staff_id(), '마감 풀기');
end $$;

alter table public.promo_weeks enable row level security;
alter table public.promo_targets enable row level security;
alter table public.promo_history enable row level security;
-- 목표와 진행 상황은 팀 전원이 봄. 고치는 건 대표·팀장 (마감은 위 함수로만)
create policy promo_weeks_select on public.promo_weeks for select to authenticated using (public.my_staff_id() is not null);
create policy promo_weeks_insert on public.promo_weeks for insert to authenticated with check (public.is_manager() and closed_at is null and results is null);
create policy promo_weeks_update on public.promo_weeks for update to authenticated using (public.is_manager())
  with check (public.is_manager());
create policy promo_targets_select on public.promo_targets for select to authenticated using (public.my_staff_id() is not null);
create policy promo_targets_insert on public.promo_targets for insert to authenticated with check (public.is_manager());
create policy promo_targets_update on public.promo_targets for update to authenticated using (public.is_manager()) with check (public.is_manager());
create policy promo_targets_remove on public.promo_targets for delete to authenticated using (public.is_manager());
create policy promo_history_select on public.promo_history for select to authenticated using (public.is_manager());

revoke all on public.promo_weeks, public.promo_targets, public.promo_history from anon;
revoke execute on function public.promo_weeks_touch(), public.promo_targets_log() from public, anon, authenticated;
revoke execute on function public.promo_close(uuid, jsonb), public.promo_reopen(uuid) from public, anon;
grant execute on function public.promo_close(uuid, jsonb), public.promo_reopen(uuid) to authenticated;
