-- 광고 수집 이전 1단계: 예전 네이버 대시보드의 광고 표를 통합 DB로 (같은 id 유지)
--   읽기: 재직 직원 (화면에서 담당 범위로 거름) · 쓰기: 대표·팀장 화면 함수 또는 수집기(토큰)만
--   비밀값(API 키)은 표에 두지 않고 금고(vault)에 둠 → ads_api_credentials 에는 금고 id와 끝 4자리만

create table public.ads_advertisers (
  id                bigint generated by default as identity primary key,
  name              text,
  customer_id       text unique,
  manager           text,
  credential_group  text,
  mapped_at         date,
  adcost_source     text not null default 'auto' check (adcost_source in ('auto','naver_api','transferred')),
  transferred_at    date,
  gfa_ad_account_no bigint,
  notes             text,
  client_id         uuid references public.clients(id) on delete set null,
  created_at        timestamptz not null default now()
);
comment on table public.ads_advertisers is '광고 계정(네이버 검색광고·GFA·메타 껍데기). 예전 advertisers 와 같은 id';

create table public.ads_groups (
  id              bigint generated by default as identity primary key,
  name            text not null,
  is_active       boolean not null default true,
  jinwon_handover boolean not null default false,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);
create table public.ads_group_members (
  advertiser_id bigint primary key references public.ads_advertisers(id) on delete cascade,
  group_id      bigint not null references public.ads_groups(id),
  created_at    timestamptz not null default now()
);
create table public.ads_group_handover_history (
  id             bigint generated by default as identity primary key,
  group_id       bigint not null references public.ads_groups(id),
  previous_value boolean not null,
  new_value      boolean not null,
  effective_date date not null,
  changed_at     timestamptz not null default now(),
  changed_by     text
);
-- 담당자 → 네이버 공용 키 묶음 (SOJUNG 등)
create table public.ads_manager_keys (
  manager          text primary key,
  credential_group text not null
);

create table public.ads_api_credentials (
  advertiser_id    bigint not null references public.ads_advertisers(id) on delete cascade,
  platform         text not null check (platform in ('naver_searchad','meta')),
  account_id       text not null,
  api_key_secret   uuid,   -- vault.secrets.id
  secret_secret    uuid not null,
  key_hint         text,
  status           text not null default 'unverified' check (status in ('valid','unverified','invalid')),
  status_message   text,
  last_verified_at timestamptz,
  updated_by       text,
  updated_at       timestamptz not null default now(),
  primary key (advertiser_id, platform)
);

create table public.ads_perf_accounts (
  id                  bigint generated by default as identity primary key,
  platform            text not null,
  external_account_id text not null,
  account_name        text,
  advertiser_id       bigint references public.ads_advertisers(id) on delete set null,
  is_active           boolean not null default true,
  created_at          timestamptz not null default now(),
  unique (platform, external_account_id)
);
create table public.ads_perf_assignments (
  id                  bigint generated by default as identity primary key,
  perf_account_id     bigint not null references public.ads_perf_accounts(id) on delete cascade,
  manager             text not null,
  valid_from          date not null,
  valid_to            date,
  allocation_rate     numeric not null default 1,
  assignment_type     text not null default 'PRIMARY',
  note                text,
  created_at          timestamptz not null default now()
);
create table public.ads_meta_accounts (
  id                  bigint generated by default as identity primary key,
  external_account_id text not null unique,
  account_name        text not null,
  perf_account_id     bigint references public.ads_perf_accounts(id) on delete set null,
  advertiser_id       bigint references public.ads_advertisers(id) on delete set null,
  currency            text,
  timezone_name       text,
  is_active           boolean not null default true,
  last_synced_at      timestamptz,
  created_at          timestamptz not null default now()
);
create table public.ads_meta_spend_daily (
  meta_account_id bigint not null references public.ads_meta_accounts(id) on delete cascade,
  stat_date       date not null,
  spend           numeric not null,
  currency        text,
  collected_at    timestamptz not null default now(),
  primary key (meta_account_id, stat_date)
);

create table public.ads_bizmoney_snapshots (
  snapshot_date       date not null,
  customer_id         text not null,
  advertiser_id       bigint,
  advertiser_name     text,
  manager             text,
  source              text,
  bizmoney            bigint,
  gross_total_cost    bigint,
  gross_daily_average bigint,
  calculation_days    integer,
  period_start        date,
  period_end          date,
  expected_days       numeric,
  status              text not null,
  reason              text,
  error               text,
  captured_at         timestamptz not null default now(),
  prev_period_start   date,
  prev_period_end     date,
  prev_active         boolean,
  prev_total_cost     bigint,
  prev_daily_average  bigint,
  key_source          text,
  primary key (snapshot_date, customer_id)
);
create table public.ads_sync_runs (
  id          bigint generated by default as identity primary key,
  job         text not null,
  run_date    date not null,
  started_at  timestamptz not null default now(),
  finished_at timestamptz,
  ok          boolean,
  summary     jsonb not null default '{}'::jsonb
);
create index ads_sync_runs_date_idx on public.ads_sync_runs(run_date, job);

create table public.ads_searchad_daily (
  customer_id               text not null,
  campaign_id               text not null,
  stat_date                 date not null,
  advertiser_id             bigint not null,
  campaign_name             text not null,
  campaign_type             text,
  campaign_type_label       text,
  impressions               bigint not null default 0,
  clicks                    bigint not null default 0,
  cost                      bigint not null default 0,
  conversions               numeric not null default 0,
  conversion_value          bigint not null default 0,
  purchase_conversions      numeric not null default 0,
  purchase_conversion_value bigint not null default 0,
  campaign_status           text,
  user_lock                 boolean,
  collected_at              timestamptz not null default now(),
  primary key (customer_id, campaign_id, stat_date)
);
create index ads_searchad_daily_date_idx on public.ads_searchad_daily(stat_date, advertiser_id);
create table public.ads_searchad_status (
  customer_id                text not null,
  stat_date                  date not null,
  advertiser_id              bigint not null,
  status                     text not null,
  discovered_campaign_count  integer not null default 0,
  successful_campaign_count  integer not null default 0,
  failed_campaign_count      integer not null default 0,
  saved_row_count            integer not null default 0,
  error_summary              text,
  first_attempted_at         timestamptz not null default now(),
  last_attempted_at          timestamptz not null default now(),
  completed_at               timestamptz,
  primary key (customer_id, stat_date)
);
create table public.ads_transferred_daily (
  customer_id       text not null,
  stat_date         date not null,
  paid_cost         bigint not null,
  advertiser_name   text,
  source_start_date date,
  source_end_date   date,
  imported_at       timestamptz not null default now(),
  primary key (customer_id, stat_date)
);
create index ads_transferred_date_idx on public.ads_transferred_daily(stat_date);

-- 메타: 담당 배정 기간 기준 담당자별 일 광고비 (예전 v_meta_employee_daily_spend 와 같은 계산)
create view public.ads_meta_manager_daily with (security_invoker = true) as
select d.stat_date, ma.id meta_account_id, ma.external_account_id, ma.account_name, ma.advertiser_id, adv.name advertiser_name,
       paa.manager, d.spend, coalesce(paa.allocation_rate, 1) allocation_rate,
       round(d.spend * coalesce(paa.allocation_rate, 1), 2) attributed_spend, d.currency
  from public.ads_meta_spend_daily d
  join public.ads_meta_accounts ma on ma.id = d.meta_account_id
  join public.ads_perf_accounts pa on pa.id = ma.perf_account_id and pa.platform = 'META'
  left join public.ads_perf_assignments paa on paa.perf_account_id = pa.id and paa.valid_from <= d.stat_date and (paa.valid_to is null or paa.valid_to >= d.stat_date)
  left join public.ads_advertisers adv on adv.id = ma.advertiser_id
 where ma.is_active;

-- 읽기 권한: 재직 직원 (비밀값 상태 표는 대표·팀장만)
do $$
declare t text;
begin
  foreach t in array array['ads_advertisers','ads_groups','ads_group_members','ads_group_handover_history','ads_manager_keys',
    'ads_perf_accounts','ads_perf_assignments','ads_meta_accounts','ads_meta_spend_daily','ads_bizmoney_snapshots','ads_sync_runs',
    'ads_searchad_daily','ads_searchad_status','ads_transferred_daily','ads_api_credentials'] loop
    execute format('alter table public.%I enable row level security', t);
    if t = 'ads_api_credentials' then
      execute format('create policy %I on public.%I for select to authenticated using (public.is_manager())', t || '_select', t);
    else
      execute format('create policy %I on public.%I for select to authenticated using (public.my_staff_id() is not null)', t || '_select', t);
    end if;
    execute format('grant select on public.%I to authenticated', t);
    execute format('create trigger zz_preview_block before insert or update or delete on public.%I for each statement execute function public.preview_block()', t);
  end loop;
end $$;
grant select on public.ads_meta_manager_daily to authenticated;
