-- 근태·연차 (예전 대시보드에서 옮김)
--   * 출근·퇴근 버튼, 지각·조퇴 자동 판정 (기본근무 / 시차근무, 반차, 직퇴·생일·프로모션 조기퇴근)
--   * 연차·반차·경조휴가·포상휴가 신청 → 1차 승인 → 최종 승인 (대표·팀장). 승인된 연차 취소도 같은 2단계
--   * 기타 근태·미팅·직퇴·조기퇴근 신청 → 승인, 근태 수정 요청 → 처리
--   * 연차 잔액(부여+조정−사용), 1년 미만 월차 자동 부여, 공휴일, 근무시간 설정
--   * 보기: 직원은 본인 것만, 대표·팀장은 전체. 승인된 휴가·공휴일·근태 예외는 달력에서 모두에게 보임
--   * 예전 대시보드 기록은 import_legacy_attendance로 옮김 (여러 번 눌러도 중복 없음, 예전 번호 legacy_id)

-- ---------------------------------------------------------------- 표
-- 인사 정보 (직원 목록은 모두가 보므로 생일·입사일·연락처는 따로 보관: 본인과 대표·팀장만)
create table public.staff_hr (
  staff_id         uuid primary key references public.staff(id) on delete cascade,
  join_date        date,
  birthday_month   int check (birthday_month between 1 and 12),
  birthday_day     int check (birthday_day between 1 and 31),
  work_type        text not null default 'standard' check (work_type in ('standard','flexible')),
  leave_grant_mode text not null default 'accounting_auto' check (leave_grant_mode in ('accounting_auto','manual')),
  work_phone       text,
  updated_at       timestamptz not null default now()
);
comment on column public.staff_hr.work_type is 'standard=기본근무, flexible=시차근무';
comment on column public.staff_hr.leave_grant_mode is 'accounting_auto=매년 1월 1일 15일 자동, manual=1년 미만 매달 1일 월차 자동(입사 다음 달 제외)';

create table public.work_settings (
  setting_key   text primary key,
  setting_label text not null,
  setting_value text not null,
  updated_at    timestamptz not null default now()
);
insert into public.work_settings(setting_key, setting_label, setting_value) values
  ('standard_clock_in', '기본 출근시간', '10:00'),
  ('standard_clock_out', '기본 퇴근시간', '19:00'),
  ('lunch_start', '점심 시작', '12:00'),
  ('lunch_end', '점심 종료', '13:00'),
  ('payday_lunch_end', '매월 25일 점심 종료', '13:30'),
  ('morning_half_clock_in', '오전반차 출근', '15:00'),
  ('morning_half_clock_out', '오전반차 퇴근', '19:00'),
  ('afternoon_half_clock_in', '오후반차 출근', '10:00'),
  ('afternoon_half_clock_out', '오후반차 퇴근', '15:00'),
  ('flexible_clock_in_start', '시차근무 출근 가능 시작', '09:00'),
  ('flexible_clock_in_end', '시차근무 출근 가능 종료', '10:00'),
  ('flexible_work_minutes', '시차근무 근무시간(분)', '540');

create table public.work_setting_history (
  id            bigint generated by default as identity primary key,
  setting_key   text not null,
  setting_label text not null,
  old_value     text,
  new_value     text,
  changed_by    uuid references public.staff(id) on delete set null,
  created_at    timestamptz not null default now()
);

create table public.company_holidays (
  holiday_date date primary key,
  holiday_name text not null,
  created_at   timestamptz not null default now()
);

create table public.leave_balances (
  id               bigint generated by default as identity primary key,
  staff_id         uuid not null references public.staff(id) on delete cascade,
  leave_year       int not null check (leave_year between 2000 and 2100),
  granted_leave    numeric not null default 0 check (granted_leave >= 0),
  adjustment_leave numeric not null default 0,
  note             text,
  created_at       timestamptz not null default now(),
  unique (staff_id, leave_year)
);

create table public.leave_balance_history (
  id                   bigint generated by default as identity primary key,
  staff_id             uuid not null references public.staff(id) on delete cascade,
  leave_year           int not null,
  old_granted_leave    numeric not null,
  new_granted_leave    numeric not null,
  old_adjustment_leave numeric not null,
  new_adjustment_leave numeric not null,
  change_note          text,
  changed_by           uuid references public.staff(id) on delete set null,
  created_at           timestamptz not null default now(),
  legacy_id            bigint unique
);

create table public.leave_monthly_grants (
  id           bigint generated by default as identity primary key,
  staff_id     uuid not null references public.staff(id) on delete cascade,
  grant_date   date not null,
  granted_days numeric(5,2) not null default 1 check (granted_days > 0),
  note         text,
  created_at   timestamptz not null default now(),
  unique (staff_id, grant_date)
);

create table public.leave_requests (
  id                  bigint generated by default as identity primary key,
  staff_id            uuid not null references public.staff(id) on delete cascade,
  leave_type          text not null check (leave_type in ('annual','morning_half','afternoon_half','family_event','reward')),
  start_date          date not null,
  end_date            date not null,
  leave_days          numeric not null default 1 check (leave_days > 0),
  deduct_leave        boolean not null default false,
  reason              text,
  status              text not null default 'pending' check (status in ('pending','first_approved','approved','rejected','cancelled')),
  first_approved_by   uuid references public.staff(id) on delete set null,
  first_approved_at   timestamptz,
  approved_by         uuid references public.staff(id) on delete set null,
  approved_at         timestamptz,
  decided_note        text,
  resubmitted_from_id bigint references public.leave_requests(id) on delete set null,
  cancel_status       text check (cancel_status in ('pending','first_approved')),
  cancel_reason       text,
  created_by          uuid references public.staff(id) on delete set null,
  created_at          timestamptz not null default now(),
  legacy_id           bigint unique
);
comment on column public.leave_requests.leave_type is 'annual=연차, morning_half=오전반차, afternoon_half=오후반차, family_event=경조휴가, reward=포상휴가';
create index leave_requests_staff_idx on public.leave_requests(staff_id, start_date);

create table public.attendance_exceptions (
  id                  bigint generated by default as identity primary key,
  staff_id            uuid not null references public.staff(id) on delete cascade,
  work_date           date not null,
  exception_type      text not null check (exception_type in ('birthday_early_leave','direct_home','meeting','other','promotion_early_leave')),
  start_time          time,
  end_time            time,
  return_to_office    boolean,
  approved_leave_time time,
  location            text,
  note                text,
  status              text not null default 'pending' check (status in ('pending','approved','rejected','cancelled')),
  approved_by         uuid references public.staff(id) on delete set null,
  created_by          uuid references public.staff(id) on delete set null,
  created_at          timestamptz not null default now(),
  legacy_id           bigint unique
);
comment on column public.attendance_exceptions.exception_type is 'birthday_early_leave=생일 조기퇴근(16시), direct_home=미팅 후 직퇴, meeting=미팅, other=기타 근태(시간 없으면 종일), promotion_early_leave=프로모션 조기퇴근';
create index attendance_exceptions_staff_idx on public.attendance_exceptions(staff_id, work_date);

create table public.attendance_records (
  id                      bigint generated by default as identity primary key,
  staff_id                uuid not null references public.staff(id) on delete cascade,
  work_date               date not null,
  clock_in                timestamptz,
  clock_out               timestamptz,
  attendance_status       text not null default 'normal' check (attendance_status in ('normal','late','early_leave','annual_leave','morning_half','afternoon_half','family_event','reward_leave','meeting','direct_home','birthday_early_leave','promotion_early_leave','absent','other')),
  is_late                 boolean not null default false,
  is_early_leave          boolean not null default false,
  note                    text,
  leave_request_id        bigint references public.leave_requests(id) on delete set null,
  attendance_exception_id bigint unique references public.attendance_exceptions(id) on delete cascade,
  created_at              timestamptz not null default now(),
  updated_at              timestamptz not null default now(),
  legacy_id               bigint unique,
  unique (staff_id, work_date)
);
create index attendance_records_date_idx on public.attendance_records(work_date);

create table public.attendance_record_history (
  id                    bigint generated by default as identity primary key,
  attendance_record_id  bigint not null references public.attendance_records(id) on delete cascade,
  staff_id              uuid not null references public.staff(id) on delete cascade,
  work_date             date not null,
  old_clock_in          timestamptz,
  new_clock_in          timestamptz,
  old_clock_out         timestamptz,
  new_clock_out         timestamptz,
  old_attendance_status text,
  new_attendance_status text,
  old_is_late           boolean,
  new_is_late           boolean,
  old_is_early_leave    boolean,
  new_is_early_leave    boolean,
  old_note              text,
  new_note              text,
  change_reason         text not null,
  changed_by            uuid references public.staff(id) on delete set null,
  created_at            timestamptz not null default now(),
  legacy_id             bigint unique
);

create table public.attendance_correction_requests (
  id                   bigint generated by default as identity primary key,
  attendance_record_id bigint not null references public.attendance_records(id) on delete cascade,
  staff_id             uuid not null references public.staff(id) on delete cascade,
  work_date            date not null,
  requested_clock_in   timestamptz,
  requested_clock_out  timestamptz,
  reason               text not null check (length(trim(reason)) > 0),
  status               text not null default 'pending' check (status in ('pending','approved','rejected')),
  processed_by         uuid references public.staff(id) on delete set null,
  processed_at         timestamptz,
  process_note         text,
  created_at           timestamptz not null default now(),
  legacy_id            bigint unique
);

-- ---------------------------------------------------------------- 공통 도우미
-- 예전 기록을 그대로 옮기는 중에는 자동 계산·검사를 건너뜀 (import_legacy_attendance 안에서만 켜짐)
create or replace function public.att_importing() returns boolean
language sql stable as $$ select coalesce(current_setting('app.att_import', true), '') = 'on' $$;

create or replace function public.att_setting(k text) returns text
language sql stable security definer set search_path = public as $$
  select setting_value from public.work_settings where setting_key = k
$$;

create or replace function public.att_is_workday(d date) returns boolean
language sql stable security definer set search_path = public as $$
  select extract(isodow from d) between 1 and 5 and not exists (select 1 from public.company_holidays where holiday_date = d)
$$;

create or replace function public.calculate_leave_days(p_start date, p_end date) returns numeric
language sql stable security definer set search_path = public as $$
  select count(*)::numeric from generate_series(p_start, p_end, interval '1 day') d where public.att_is_workday(d::date)
$$;

create or replace function public.att_work_type(p_staff uuid) returns text
language sql stable security definer set search_path = public as $$
  select coalesce((select work_type from public.staff_hr where staff_id = p_staff), 'standard')
$$;

-- 출퇴근 시각으로 근태 상태·지각·조퇴 판정 (출근·퇴근 버튼, 관리자 수정, 수정 요청 승인 모두 같은 기준)
create or replace function public.att_evaluate(p_staff uuid, p_date date, p_in timestamptz, p_out timestamptz,
  out status text, out is_late boolean, out is_early boolean)
language plpgsql stable security definer set search_path = public as $$
declare
  wt text := public.att_work_type(p_staff);
  half text; ex_type text; ex_time time;
  t_in time; t_out time;
begin
  select lr.leave_type into half from public.leave_requests lr
   where lr.staff_id = p_staff and lr.status = 'approved' and p_date between lr.start_date and lr.end_date
     and lr.leave_type in ('morning_half','afternoon_half') order by lr.id desc limit 1;
  select ae.exception_type, ae.approved_leave_time into ex_type, ex_time from public.attendance_exceptions ae
   where ae.staff_id = p_staff and ae.work_date = p_date and ae.status = 'approved'
     and ae.exception_type in ('direct_home','birthday_early_leave','promotion_early_leave') order by ae.id desc limit 1;

  status := coalesce(ex_type, half, 'normal');
  is_late := false; is_early := false;

  if p_in is not null then
    t_in := timezone('Asia/Seoul', p_in)::time;
    if half = 'morning_half' then is_late := t_in > public.att_setting('morning_half_clock_in')::time;
    elsif wt = 'flexible' then is_late := t_in > public.att_setting('flexible_clock_in_end')::time;
    else is_late := t_in > public.att_setting('standard_clock_in')::time;
    end if;
  end if;

  if p_out is not null then
    t_out := timezone('Asia/Seoul', p_out)::time;
    if ex_type = 'direct_home' then is_early := false;
    elsif ex_type in ('birthday_early_leave','promotion_early_leave') then
      if ex_time is null then raise exception '승인된 조기퇴근의 퇴근시간 정보가 없습니다'; end if;
      is_early := t_out < ex_time;
    elsif half = 'afternoon_half' then is_early := t_out < public.att_setting('afternoon_half_clock_out')::time;
    elsif half = 'morning_half' or wt = 'standard' then is_early := t_out < public.att_setting('standard_clock_out')::time;
    elsif p_in is not null then
      is_early := timezone('Asia/Seoul', p_out) < timezone('Asia/Seoul', p_in) + make_interval(mins => public.att_setting('flexible_work_minutes')::int);
    end if;
  end if;
end
$$;

-- ---------------------------------------------------------------- 휴가 신청 자동 계산·검사
create or replace function public.leave_requests_before() returns trigger
language plpgsql security definer set search_path = public as $$
declare total numeric; used numeric;
begin
  if public.att_importing() then return new; end if;
  if tg_op = 'INSERT' then new.created_by := coalesce(public.my_staff_id(), new.created_by); end if;

  -- 일수: 반차 0.5일, 나머지는 주말·공휴일을 뺀 근무일 수
  if new.start_date > new.end_date then raise exception '종료일은 시작일보다 빠를 수 없습니다'; end if;
  if new.leave_type in ('morning_half','afternoon_half') then
    if new.start_date <> new.end_date then raise exception '반차는 하루 단위로만 신청할 수 있습니다'; end if;
    new.leave_days := 0.5; new.deduct_leave := true;
  else
    new.leave_days := public.calculate_leave_days(new.start_date, new.end_date);
    if new.leave_days <= 0 then raise exception '선택한 기간에 실제 근무일이 없습니다'; end if;
    if new.leave_type = 'annual' then new.deduct_leave := true;
    elsif new.leave_type = 'family_event' then new.deduct_leave := false;
    end if; -- 포상휴가는 승인할 때 차감 여부를 고름
  end if;

  if new.status in ('pending','first_approved','approved') then
    if extract(year from new.start_date) <> extract(year from new.end_date) then
      raise exception '휴가는 연도를 넘겨서 한 번에 신청할 수 없습니다';
    end if;
    -- 겹치는 날짜
    if exists (select 1 from public.leave_requests lr where lr.staff_id = new.staff_id and lr.id is distinct from new.id
                and lr.status in ('pending','first_approved','approved')
                and new.start_date <= lr.end_date and new.end_date >= lr.start_date) then
      raise exception '이미 해당 날짜에 신청 또는 승인된 휴가가 있습니다';
    end if;
    -- 잔여 연차 (신청 중인 것까지 포함)
    if new.deduct_leave then
      select granted_leave + adjustment_leave into total from public.leave_balances
       where staff_id = new.staff_id and leave_year = extract(year from new.start_date)::int;
      if total is null then raise exception '해당 연도의 연차 부여 정보가 없습니다. 대표·팀장에게 연차 등록을 요청해 주세요'; end if;
      select coalesce(sum(leave_days), 0) into used from public.leave_requests
       where staff_id = new.staff_id and extract(year from start_date) = extract(year from new.start_date)
         and deduct_leave and status in ('pending','first_approved','approved') and id is distinct from new.id;
      if new.leave_days > total - used then
        raise exception '잔여 연차가 부족합니다. 신청 가능 연차: %일', total - used;
      end if;
    end if;
  end if;
  return new;
end
$$;
create trigger leave_requests_before before insert or update on public.leave_requests
  for each row execute function public.leave_requests_before();

-- 최종 승인된 종일 휴가(연차·경조·포상)는 그날 근태 기록을 자동으로 만들고, 취소·반려되면 지움
create or replace function public.leave_requests_sync_attendance() returns trigger
language plpgsql security definer set search_path = public as $$
declare d date; st text; nt text;
begin
  if public.att_importing() then return new; end if;
  if new.leave_type not in ('annual','family_event','reward') then return new; end if;
  if tg_op = 'UPDATE' and old.status = new.status and old.start_date = new.start_date and old.end_date = new.end_date
     and old.leave_type = new.leave_type then
    return new;
  end if;
  st := case new.leave_type when 'family_event' then 'family_event' when 'reward' then 'reward_leave' else 'annual_leave' end;
  nt := case new.leave_type when 'family_event' then '승인된 경조휴가' when 'reward' then '승인된 포상휴가' else '승인된 종일 연차' end;
  delete from public.attendance_records
   where leave_request_id = new.id and attendance_status in ('annual_leave','family_event','reward_leave')
     and clock_in is null and clock_out is null;
  if new.status = 'approved' then
    for d in select g::date from generate_series(new.start_date, new.end_date, interval '1 day') g where public.att_is_workday(g::date) loop
      if exists (select 1 from public.attendance_records where staff_id = new.staff_id and work_date = d) then
        raise exception '% 날짜에 이미 근태 기록이 있어 종일 휴가를 승인할 수 없습니다', d;
      end if;
      insert into public.attendance_records(staff_id, work_date, attendance_status, note, leave_request_id)
      values (new.staff_id, d, st, nt, new.id);
    end loop;
  end if;
  return new;
end
$$;
create trigger leave_requests_sync_attendance after insert or update on public.leave_requests
  for each row execute function public.leave_requests_sync_attendance();

-- ---------------------------------------------------------------- 근태 예외 검사
create or replace function public.attendance_exceptions_before() returns trigger
language plpgsql security definer set search_path = public as $$
declare bm int;
begin
  if public.att_importing() then return new; end if;
  if tg_op = 'INSERT' then new.created_by := coalesce(public.my_staff_id(), new.created_by); end if;
  if new.status = 'approved' and new.approved_by is null then new.approved_by := public.my_staff_id(); end if;

  if new.exception_type in ('other','meeting','direct_home') and nullif(trim(coalesce(new.note, '')), '') is null then
    raise exception '%', case when new.exception_type = 'other' then '기타 근태의 상세 내용을 입력해 주세요' else '미팅 내용을 입력해 주세요' end;
  end if;
  if new.start_time is not null and new.end_time is not null and new.end_time <= new.start_time then
    raise exception '종료시간은 시작시간보다 늦어야 합니다';
  end if;
  if new.exception_type in ('meeting','direct_home') then
    if new.start_time is null then raise exception '미팅 시작시간을 입력해 주세요'; end if;
    if nullif(trim(coalesce(new.location, '')), '') is null then raise exception '미팅 장소를 입력해 주세요'; end if;
    new.return_to_office := new.exception_type = 'meeting';
  end if;
  if new.exception_type = 'promotion_early_leave' then
    if new.approved_leave_time is null then raise exception '프로모션 조기퇴근은 퇴근시간을 입력해 주세요'; end if;
    if nullif(trim(coalesce(new.note, '')), '') is null then raise exception '프로모션 조기퇴근 사유를 입력해 주세요'; end if;
  end if;
  if new.exception_type = 'birthday_early_leave' then
    select birthday_month into bm from public.staff_hr where staff_id = new.staff_id;
    if bm is null then raise exception '생일 정보가 등록되어 있지 않습니다. 대표·팀장에게 등록을 요청해 주세요'; end if;
    if extract(month from new.work_date) <> bm then raise exception '생일 조기퇴근은 생일이 있는 달에만 쓸 수 있습니다'; end if;
    if not public.att_is_workday(new.work_date) then raise exception '생일 조기퇴근은 평일 근무일에만 쓸 수 있습니다'; end if;
    new.approved_leave_time := '16:00';
    if new.status in ('pending','approved') and exists (
      select 1 from public.attendance_exceptions ae where ae.staff_id = new.staff_id and ae.exception_type = 'birthday_early_leave'
         and ae.status in ('pending','approved') and extract(year from ae.work_date) = extract(year from new.work_date) and ae.id is distinct from new.id) then
      raise exception '생일 조기퇴근은 1년에 한 번만 쓸 수 있습니다';
    end if;
  end if;
  if new.status in ('pending','approved') and new.exception_type in ('direct_home','birthday_early_leave','promotion_early_leave')
     and exists (select 1 from public.attendance_exceptions ae where ae.staff_id = new.staff_id and ae.work_date = new.work_date
                  and ae.status in ('pending','approved') and ae.exception_type in ('direct_home','birthday_early_leave','promotion_early_leave')
                  and ae.id is distinct from new.id) then
    raise exception '그날 이미 직퇴 또는 조기퇴근 신청이 있습니다';
  end if;
  return new;
end
$$;
create trigger attendance_exceptions_before before insert or update on public.attendance_exceptions
  for each row execute function public.attendance_exceptions_before();

-- 승인된 '종일' 기타 근태(시간 없음)는 그날 근태 기록을 자동으로 만들고, 취소되면 지움
create or replace function public.attendance_exceptions_sync() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  if public.att_importing() then return coalesce(new, old); end if;
  if tg_op = 'DELETE' then
    delete from public.attendance_records where attendance_exception_id = old.id;
    return old;
  end if;
  delete from public.attendance_records where attendance_exception_id = new.id and clock_in is null and clock_out is null;
  if new.exception_type <> 'other' or new.status <> 'approved' or new.start_time is not null or new.end_time is not null then
    return new;
  end if;
  if not public.att_is_workday(new.work_date) then raise exception '종일 기타 근태는 평일 근무일만 승인할 수 있습니다'; end if;
  if exists (select 1 from public.attendance_records where staff_id = new.staff_id and work_date = new.work_date) then
    raise exception '그날 이미 출퇴근 또는 휴가 기록이 있어 종일 기타 근태를 승인할 수 없습니다';
  end if;
  insert into public.attendance_records(staff_id, work_date, attendance_status, note, attendance_exception_id)
  values (new.staff_id, new.work_date, 'other', '승인된 종일 기타 근태: ' || coalesce(new.note, ''), new.id);
  return new;
end
$$;
create trigger attendance_exceptions_sync after insert or update or delete on public.attendance_exceptions
  for each row execute function public.attendance_exceptions_sync();

-- 승인된 종일 휴가가 있는 날에는 출근 시각을 넣을 수 없음
create or replace function public.attendance_records_before() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  if public.att_importing() then return new; end if;
  new.updated_at := now();
  if new.clock_in is not null and exists (
    select 1 from public.leave_requests lr where lr.staff_id = new.staff_id and lr.status = 'approved'
       and lr.leave_type in ('annual','family_event','reward') and new.work_date between lr.start_date and lr.end_date) then
    raise exception '승인된 종일 휴가가 있는 날에는 출근할 수 없습니다';
  end if;
  return new;
end
$$;
create trigger attendance_records_before before insert or update on public.attendance_records
  for each row execute function public.attendance_records_before();

-- ---------------------------------------------------------------- 출근·퇴근
-- 시각을 받는 안쪽 함수 (시험용). 화면에서는 clock_in()/clock_out()만 씀
create or replace function public.att_clock_in(p_staff uuid, p_at timestamptz) returns public.attendance_records
language plpgsql security definer set search_path = public as $$
declare d date := timezone('Asia/Seoul', p_at)::date; lt text; ev record; r public.attendance_records;
begin
  if not exists (select 1 from public.staff where id = p_staff and is_active) then raise exception '재직 중인 직원이 아닙니다'; end if;
  if extract(isodow from d) not between 1 and 5 then raise exception '주말에는 출근 처리할 수 없습니다'; end if;
  if exists (select 1 from public.company_holidays where holiday_date = d) then raise exception '공휴일·회사 휴무일에는 출근 처리할 수 없습니다'; end if;
  select leave_type into lt from public.leave_requests where staff_id = p_staff and status = 'approved'
     and d between start_date and end_date and leave_type in ('annual','family_event','reward') order by id desc limit 1;
  if lt is not null then
    raise exception '승인된 %가 있는 날에는 출근할 수 없습니다', case lt when 'annual' then '종일 연차' when 'family_event' then '경조휴가' else '포상휴가' end;
  end if;
  if exists (select 1 from public.attendance_exceptions where staff_id = p_staff and work_date = d and exception_type = 'other'
              and status = 'approved' and start_time is null and end_time is null) then
    raise exception '승인된 종일 기타 근태가 있는 날에는 출근할 수 없습니다';
  end if;
  select * into r from public.attendance_records where staff_id = p_staff and work_date = d;
  if found and r.clock_in is not null then return r; end if; -- 이미 출근: 처음 시각 유지
  if found and r.clock_in is null and r.attendance_status in ('annual_leave','family_event','reward_leave','other') then
    raise exception '오늘은 출퇴근 처리가 필요 없는 승인 근태일입니다';
  end if;
  ev := public.att_evaluate(p_staff, d, p_at, null);
  insert into public.attendance_records(staff_id, work_date, clock_in, attendance_status, is_late)
  values (p_staff, d, p_at, ev.status, ev.is_late)
  on conflict (staff_id, work_date) do update set clock_in = excluded.clock_in, attendance_status = excluded.attendance_status, is_late = excluded.is_late
  returning * into r;
  return r;
end
$$;

create or replace function public.att_clock_out(p_staff uuid, p_at timestamptz) returns public.attendance_records
language plpgsql security definer set search_path = public as $$
declare d date := timezone('Asia/Seoul', p_at)::date; ev record; r public.attendance_records;
begin
  select * into r from public.attendance_records where staff_id = p_staff and work_date = d;
  if not found or r.clock_in is null then raise exception '오늘 출근 기록이 없습니다'; end if;
  if r.clock_out is not null then return r; end if; -- 이미 퇴근: 처음 시각 유지
  ev := public.att_evaluate(p_staff, d, r.clock_in, p_at);
  update public.attendance_records set clock_out = p_at, attendance_status = ev.status, is_early_leave = ev.is_early
   where id = r.id returning * into r;
  return r;
end
$$;
revoke execute on function public.att_clock_in(uuid, timestamptz), public.att_clock_out(uuid, timestamptz) from public, anon, authenticated;

create or replace function public.att_check_self(p_staff uuid) returns uuid
language plpgsql stable security definer set search_path = public as $$
declare me uuid := public.my_staff_id();
begin
  if me is null then raise exception '로그인된 직원 정보를 확인할 수 없습니다'; end if;
  if coalesce(p_staff, me) <> me and not public.is_manager() then raise exception '본인 기록만 처리할 수 있습니다'; end if;
  return coalesce(p_staff, me);
end
$$;

create or replace function public.clock_in(p_staff uuid default null) returns public.attendance_records
language sql security definer set search_path = public as $$ select public.att_clock_in(public.att_check_self(p_staff), now()) $$;
create or replace function public.clock_out(p_staff uuid default null) returns public.attendance_records
language sql security definer set search_path = public as $$ select public.att_clock_out(public.att_check_self(p_staff), now()) $$;

-- ---------------------------------------------------------------- 휴가 결재
-- p_action: first(1차 승인) / final(최종 승인) / reject(반려). 포상휴가는 승인할 때 연차 차감 여부(p_deduct)를 정함
create or replace function public.leave_decide(p_id bigint, p_action text, p_deduct boolean default null, p_note text default null)
returns public.leave_requests
language plpgsql security definer set search_path = public as $$
declare r public.leave_requests; me uuid := public.my_staff_id();
begin
  if not public.is_manager() then raise exception '대표·팀장만 승인할 수 있습니다'; end if;
  select * into r from public.leave_requests where id = p_id for update;
  if not found then raise exception '휴가 신청을 찾을 수 없습니다'; end if;
  if p_action = 'first' then
    if r.status <> 'pending' then raise exception '이미 처리된 신청입니다'; end if;
    update public.leave_requests set status = 'first_approved', first_approved_by = me, first_approved_at = now(),
           deduct_leave = case when leave_type = 'reward' and p_deduct is not null then p_deduct else deduct_leave end
     where id = p_id returning * into r;
  elsif p_action = 'final' then
    if r.status <> 'first_approved' then raise exception '1차 승인된 신청만 최종 승인할 수 있습니다'; end if;
    update public.leave_requests set status = 'approved', approved_by = me, approved_at = now(),
           deduct_leave = case when leave_type = 'reward' and p_deduct is not null then p_deduct else deduct_leave end
     where id = p_id returning * into r;
  elsif p_action = 'reject' then
    if r.status not in ('pending','first_approved') then raise exception '반려할 수 있는 신청이 아닙니다'; end if;
    update public.leave_requests set status = 'rejected', decided_note = nullif(trim(p_note), '') where id = p_id returning * into r;
  else
    raise exception '처리 방법이 올바르지 않습니다';
  end if;
  return r;
end
$$;

-- 본인이 결재 전(1차 승인 전·후) 신청을 거둬들임
create or replace function public.leave_withdraw(p_id bigint) returns public.leave_requests
language plpgsql security definer set search_path = public as $$
declare r public.leave_requests;
begin
  update public.leave_requests set status = 'cancelled'
   where id = p_id and staff_id = public.my_staff_id() and status in ('pending','first_approved') returning * into r;
  if not found then raise exception '거둬들일 수 있는 신청이 아닙니다 (최종 승인된 휴가는 취소 요청을 해 주세요)'; end if;
  return r;
end
$$;

-- 최종 승인된 휴가 취소: 본인이 요청 → 1차 → 최종 (최종 승인 전까지 휴가는 그대로 유지)
create or replace function public.leave_cancel_request(p_id bigint, p_reason text) returns public.leave_requests
language plpgsql security definer set search_path = public as $$
declare r public.leave_requests;
begin
  if nullif(trim(coalesce(p_reason, '')), '') is null then raise exception '취소 사유를 입력해 주세요'; end if;
  update public.leave_requests set cancel_status = 'pending', cancel_reason = trim(p_reason)
   where id = p_id and staff_id = public.my_staff_id() and status = 'approved' and cancel_status is null returning * into r;
  if not found then raise exception '최종 승인된 본인 휴가만 취소 요청할 수 있습니다 (이미 요청했으면 결재를 기다려 주세요)'; end if;
  return r;
end
$$;

create or replace function public.leave_cancel_decide(p_id bigint, p_action text) returns public.leave_requests
language plpgsql security definer set search_path = public as $$
declare r public.leave_requests;
begin
  if not public.is_manager() then raise exception '대표·팀장만 처리할 수 있습니다'; end if;
  select * into r from public.leave_requests where id = p_id for update;
  if not found or r.status <> 'approved' or r.cancel_status is null then raise exception '처리할 취소 요청이 없습니다'; end if;
  if p_action = 'first' and r.cancel_status = 'pending' then
    update public.leave_requests set cancel_status = 'first_approved' where id = p_id returning * into r;
  elsif p_action = 'final' and r.cancel_status = 'first_approved' then
    update public.leave_requests set status = 'cancelled', cancel_status = null where id = p_id returning * into r;
  elsif p_action = 'reject' then
    update public.leave_requests set cancel_status = null, cancel_reason = null where id = p_id returning * into r;
  else
    raise exception '지금 상태에서는 그렇게 처리할 수 없습니다';
  end if;
  return r;
end
$$;

-- ---------------------------------------------------------------- 근태 예외 결재
-- approve / reject / cancel(승인 취소, 대표·팀장) / withdraw(본인이 승인 전 신청 거둬들이기)
create or replace function public.attendance_exception_decide(p_id bigint, p_action text) returns public.attendance_exceptions
language plpgsql security definer set search_path = public as $$
declare r public.attendance_exceptions;
begin
  select * into r from public.attendance_exceptions where id = p_id for update;
  if not found then raise exception '신청을 찾을 수 없습니다'; end if;
  if p_action = 'withdraw' then
    if r.staff_id <> public.my_staff_id() or r.status <> 'pending' then raise exception '승인 전 본인 신청만 거둬들일 수 있습니다'; end if;
    update public.attendance_exceptions set status = 'cancelled' where id = p_id returning * into r;
    return r;
  end if;
  if not public.is_manager() then raise exception '대표·팀장만 처리할 수 있습니다'; end if;
  if p_action = 'approve' and r.status = 'pending' then
    update public.attendance_exceptions set status = 'approved', approved_by = public.my_staff_id() where id = p_id returning * into r;
  elsif p_action = 'reject' and r.status = 'pending' then
    update public.attendance_exceptions set status = 'rejected' where id = p_id returning * into r;
  elsif p_action = 'cancel' and r.status = 'approved' then
    update public.attendance_exceptions set status = 'cancelled', approved_by = null where id = p_id returning * into r;
  else
    raise exception '지금 상태에서는 그렇게 처리할 수 없습니다';
  end if;
  return r;
end
$$;

-- ---------------------------------------------------------------- 근태 기록 수정 (대표·팀장)
-- 그날 기록이 없으면 새로 만듦. 지각·조퇴는 같은 기준으로 다시 판정하고 변경 이력을 남김
create or replace function public.attendance_record_save(p_staff uuid, p_date date, p_in timestamptz, p_out timestamptz,
  p_note text, p_reason text) returns public.attendance_records
language plpgsql security definer set search_path = public as $$
declare r public.attendance_records; ev record; was_new boolean := false;
begin
  if not public.is_manager() then raise exception '대표·팀장만 근태 기록을 고칠 수 있습니다'; end if;
  if nullif(trim(coalesce(p_reason, '')), '') is null then raise exception '수정 사유를 입력해 주세요'; end if;
  if p_in is null and p_out is not null then raise exception '출근시간 없이 퇴근시간만 넣을 수 없습니다'; end if;
  if p_in is not null and p_out is not null and p_out < p_in then raise exception '퇴근시간은 출근시간보다 빠를 수 없습니다'; end if;
  select * into r from public.attendance_records where staff_id = p_staff and work_date = p_date for update;
  if found then
    if r.clock_in is null and r.clock_out is null and (r.leave_request_id is not null or r.attendance_exception_id is not null
       or r.attendance_status in ('annual_leave','family_event','reward_leave','other')) then
      raise exception '휴가·종일 기타 근태로 만들어진 기록은 직접 고칠 수 없습니다. 원래 신청을 취소해 주세요';
    end if;
  else
    insert into public.attendance_records(staff_id, work_date) values (p_staff, p_date) returning * into r;
    was_new := true;
  end if;
  ev := public.att_evaluate(p_staff, p_date, p_in, p_out);
  if not was_new and r.clock_in is not distinct from p_in and r.clock_out is not distinct from p_out
     and r.note is not distinct from nullif(trim(p_note), '') and r.attendance_status = ev.status
     and r.is_late = ev.is_late and r.is_early_leave = ev.is_early then
    return r;
  end if;
  insert into public.attendance_record_history(attendance_record_id, staff_id, work_date, old_clock_in, new_clock_in, old_clock_out, new_clock_out,
    old_attendance_status, new_attendance_status, old_is_late, new_is_late, old_is_early_leave, new_is_early_leave, old_note, new_note, change_reason, changed_by)
  values (r.id, p_staff, p_date, case when was_new then null else r.clock_in end, p_in, case when was_new then null else r.clock_out end, p_out,
    case when was_new then null else r.attendance_status end, ev.status, r.is_late, ev.is_late, r.is_early_leave, ev.is_early,
    r.note, nullif(trim(p_note), ''), trim(p_reason), public.my_staff_id());
  update public.attendance_records set clock_in = p_in, clock_out = p_out, attendance_status = ev.status, is_late = ev.is_late,
         is_early_leave = ev.is_early, note = nullif(trim(p_note), '')
   where id = r.id returning * into r;
  return r;
end
$$;

-- 직원이 본인 근태 수정 요청 (출퇴근 버튼을 잘못 눌렀을 때 등)
create or replace function public.attendance_correction_request(p_record bigint, p_in timestamptz, p_out timestamptz, p_reason text)
returns public.attendance_correction_requests
language plpgsql security definer set search_path = public as $$
declare a public.attendance_records; r public.attendance_correction_requests;
begin
  select * into a from public.attendance_records where id = p_record;
  if not found then raise exception '근태 기록을 찾을 수 없습니다'; end if;
  if a.staff_id is distinct from public.my_staff_id() then raise exception '본인 근태 기록만 수정 요청할 수 있습니다'; end if;
  if nullif(trim(coalesce(p_reason, '')), '') is null then raise exception '수정 사유를 입력해 주세요'; end if;
  if p_in is not null and p_out is not null and p_out <= p_in then raise exception '퇴근시간은 출근시간보다 늦어야 합니다'; end if;
  if exists (select 1 from public.attendance_correction_requests where attendance_record_id = p_record and status = 'pending') then
    raise exception '이미 처리 대기 중인 수정 요청이 있습니다';
  end if;
  insert into public.attendance_correction_requests(attendance_record_id, staff_id, work_date, requested_clock_in, requested_clock_out, reason)
  values (p_record, a.staff_id, a.work_date, p_in, p_out, trim(p_reason)) returning * into r;
  return r;
end
$$;

create or replace function public.attendance_correction_decide(p_id bigint, p_action text, p_note text default null)
returns public.attendance_correction_requests
language plpgsql security definer set search_path = public as $$
declare r public.attendance_correction_requests; a public.attendance_records;
begin
  if not public.is_manager() then raise exception '대표·팀장만 처리할 수 있습니다'; end if;
  select * into r from public.attendance_correction_requests where id = p_id for update;
  if not found then raise exception '수정 요청을 찾을 수 없습니다'; end if;
  if r.status <> 'pending' then raise exception '이미 처리된 요청입니다'; end if;
  if p_action = 'approved' then
    select * into a from public.attendance_records where id = r.attendance_record_id;
    perform public.attendance_record_save(r.staff_id, r.work_date, r.requested_clock_in, r.requested_clock_out, a.note, '수정 요청 승인: ' || r.reason);
  elsif p_action <> 'rejected' then
    raise exception '처리 방법이 올바르지 않습니다';
  end if;
  update public.attendance_correction_requests set status = p_action, processed_by = public.my_staff_id(), processed_at = now(),
         process_note = nullif(trim(coalesce(p_note, '')), '')
   where id = p_id returning * into r;
  return r;
end
$$;

-- ---------------------------------------------------------------- 연차 잔액
create or replace function public.leave_balance_set(p_staff uuid, p_year int, p_granted numeric, p_adjust numeric, p_note text default null)
returns void
language plpgsql security definer set search_path = public as $$
declare og numeric; oa numeric; used numeric;
begin
  if not public.is_manager() then raise exception '대표·팀장만 연차를 고칠 수 있습니다'; end if;
  if p_granted is null or p_granted < 0 then raise exception '기본 부여 연차는 0 이상이어야 합니다'; end if;
  if p_adjust is null then raise exception '추가·조정 연차를 입력해 주세요 (없으면 0)'; end if;
  select coalesce(sum(leave_days), 0) into used from public.leave_requests
   where staff_id = p_staff and extract(year from start_date) = p_year and status = 'approved' and deduct_leave;
  if p_granted + p_adjust < used then raise exception '총 연차를 이미 쓴 연차(%일)보다 낮게 할 수 없습니다', used; end if;
  select granted_leave, adjustment_leave into og, oa from public.leave_balances where staff_id = p_staff and leave_year = p_year for update;
  if og = p_granted and oa = p_adjust then return; end if;
  insert into public.leave_balances(staff_id, leave_year, granted_leave, adjustment_leave) values (p_staff, p_year, p_granted, p_adjust)
  on conflict (staff_id, leave_year) do update set granted_leave = excluded.granted_leave, adjustment_leave = excluded.adjustment_leave;
  insert into public.leave_balance_history(staff_id, leave_year, old_granted_leave, new_granted_leave, old_adjustment_leave, new_adjustment_leave, change_note, changed_by)
  values (p_staff, p_year, coalesce(og, 0), p_granted, coalesce(oa, 0), p_adjust, nullif(trim(coalesce(p_note, '')), ''), public.my_staff_id());
end
$$;

-- 연차 현황: 총(부여+조정) / 사용(최종 승인) / 결재 중 / 남은 연차. 직원은 본인 것만
create or replace function public.leave_summary(p_year int)
returns table(staff_id uuid, staff_name text, is_active boolean, granted numeric, adjustment numeric, used numeric, pending numeric, remaining numeric)
language sql stable security definer set search_path = public as $$
  select s.id, s.name, s.is_active, coalesce(b.granted_leave, 0), coalesce(b.adjustment_leave, 0),
         coalesce(u.used, 0), coalesce(u.pending, 0),
         coalesce(b.granted_leave, 0) + coalesce(b.adjustment_leave, 0) - coalesce(u.used, 0) - coalesce(u.pending, 0)
    from public.staff s
    left join public.leave_balances b on b.staff_id = s.id and b.leave_year = p_year
    left join lateral (
      select sum(leave_days) filter (where status = 'approved') used,
             sum(leave_days) filter (where status in ('pending','first_approved')) pending
        from public.leave_requests lr where lr.staff_id = s.id and lr.deduct_leave and extract(year from lr.start_date) = p_year
    ) u on true
   where (s.id = public.my_staff_id() or public.is_manager())
     and (s.is_active or b.staff_id is not null)
   order by s.is_active desc, s.name
$$;

-- ---------------------------------------------------------------- 근무 설정 (대표·팀장)
create or replace function public.work_setting_set(p_key text, p_value text) returns void
language plpgsql security definer set search_path = public as $$
declare old_v text; lbl text; v text;
begin
  if not public.is_manager() then raise exception '대표·팀장만 근무 설정을 고칠 수 있습니다'; end if;
  select setting_value, setting_label into old_v, lbl from public.work_settings where setting_key = p_key for update;
  if not found then raise exception '없는 설정입니다'; end if;
  if p_key = 'flexible_work_minutes' then
    if coalesce(trim(p_value), '') !~ '^\d+$' or trim(p_value)::int <= 0 then raise exception '근무시간은 분 단위 숫자로 입력해 주세요'; end if;
    v := trim(p_value)::int::text;
  else
    if coalesce(trim(p_value), '') !~ '^\d{1,2}:\d{2}(:\d{2})?$' then raise exception '시간은 HH:MM 형식으로 입력해 주세요'; end if;
    v := to_char(trim(p_value)::time, 'HH24:MI');
  end if;
  if v = old_v then return; end if;
  update public.work_settings set setting_value = v, updated_at = now() where setting_key = p_key;
  insert into public.work_setting_history(setting_key, setting_label, old_value, new_value, changed_by) values (p_key, lbl, old_v, v, public.my_staff_id());
end
$$;

-- ---------------------------------------------------------------- 달력 (모두: 승인된 휴가·공휴일·근태 예외 / 대표·팀장: 출퇴근 기록까지)
create or replace function public.att_calendar(p_start date, p_end date)
returns table(event_date date, staff_id uuid, staff_name text, source text, event_type text, label text,
              clock_in timestamptz, clock_out timestamptz, is_late boolean, is_early_leave boolean)
language plpgsql stable security definer set search_path = public as $$
begin
  if public.my_staff_id() is null then raise exception '로그인한 직원만 볼 수 있습니다'; end if;
  if p_end < p_start or p_end - p_start > 62 then raise exception '한 번에 63일까지만 볼 수 있습니다'; end if;
  return query
  select g::date, s.id, s.name, 'leave'::text, lr.leave_type,
         case lr.leave_type when 'annual' then '연차' when 'morning_half' then '오전반차' when 'afternoon_half' then '오후반차'
                            when 'family_event' then '경조휴가' else '포상휴가' end,
         null::timestamptz, null::timestamptz, false, false
    from public.leave_requests lr join public.staff s on s.id = lr.staff_id
    cross join lateral generate_series(greatest(lr.start_date, p_start), least(lr.end_date, p_end), interval '1 day') g
   where lr.status = 'approved' and lr.start_date <= p_end and lr.end_date >= p_start and public.att_is_workday(g::date);
  return query
  select h.holiday_date, null::uuid, null::text, 'holiday'::text, 'holiday'::text, h.holiday_name,
         null::timestamptz, null::timestamptz, false, false
    from public.company_holidays h where h.holiday_date between p_start and p_end;
  return query
  select ae.work_date, s.id, s.name, 'exception'::text, ae.exception_type,
         case ae.exception_type when 'birthday_early_leave' then '생일 조기퇴근' when 'promotion_early_leave' then '프로모션 조기퇴근'
                                when 'direct_home' then '미팅 후 직퇴' when 'meeting' then '미팅' else '기타 근태' end,
         null::timestamptz, null::timestamptz, false, false
    from public.attendance_exceptions ae join public.staff s on s.id = ae.staff_id
   where ae.status = 'approved' and ae.work_date between p_start and p_end;
  if public.is_manager() then
    return query
    select ar.work_date, s.id, s.name, 'attendance'::text, ar.attendance_status,
           case when ar.is_late and ar.is_early_leave then '지각·조퇴' when ar.is_late then '지각' when ar.is_early_leave then '조퇴' else '출근' end,
           ar.clock_in, ar.clock_out, ar.is_late, ar.is_early_leave
      from public.attendance_records ar join public.staff s on s.id = ar.staff_id
     where ar.work_date between p_start and p_end and ar.clock_in is not null;
  end if;
end
$$;

-- ---------------------------------------------------------------- 월차·연차 자동 부여 (매달 1일 자동 실행)
--   회계연도 방식: 1월 1일에 그해 15일 (이미 있으면 건너뜀)
--   1년 미만(manual): 입사 다음다음 달부터 매달 1일 1일씩 (입사한 달 다음 달 1일은 건너뜀, 예전 대시보드와 같음)
create or replace function public.auto_grant_annual_leave(p_target date default (timezone('Asia/Seoul', now()))::date)
returns table(staff_id uuid, staff_name text, grant_type text, granted_days numeric, leave_year int)
language plpgsql security definer set search_path = public as $$
declare e record; y int := extract(year from p_target)::int;
begin
  if extract(day from p_target) <> 1 then return; end if;
  for e in select s.id, s.name, h.join_date, h.leave_grant_mode from public.staff s join public.staff_hr h on h.staff_id = s.id where s.is_active loop
    if e.leave_grant_mode = 'accounting_auto' and extract(month from p_target) = 1
       and not exists (select 1 from public.leave_balances b where b.staff_id = e.id and b.leave_year = y) then
      insert into public.leave_balances(staff_id, leave_year, granted_leave, note) values (e.id, y, 15, '회계연도 자동 부여');
      staff_id := e.id; staff_name := e.name; grant_type := 'accounting_auto'; granted_days := 15; leave_year := y; return next;
    end if;
    if e.leave_grant_mode = 'manual' and e.join_date is not null and p_target > e.join_date
       and p_target < (e.join_date + interval '1 year')::date
       and (extract(year from p_target) > extract(year from e.join_date)
            or extract(month from p_target) > extract(month from e.join_date) + 1)
       and not exists (select 1 from public.leave_monthly_grants g where g.staff_id = e.id and g.grant_date = p_target) then
      insert into public.leave_monthly_grants(staff_id, grant_date, granted_days, note) values (e.id, p_target, 1, '1년 미만 월차 자동 부여');
      insert into public.leave_balances(staff_id, leave_year, granted_leave, note) values (e.id, y, 1, '1년 미만 월차 자동 부여')
      on conflict on constraint leave_balances_staff_id_leave_year_key do update set granted_leave = public.leave_balances.granted_leave + 1;
      staff_id := e.id; staff_name := e.name; grant_type := 'manual_monthly'; granted_days := 1; leave_year := y; return next;
    end if;
  end loop;
end
$$;
revoke execute on function public.auto_grant_annual_leave(date) from public, anon, authenticated;

-- 매달 1일 0시 5분(한국 시간) 자동 실행. 시험용 데이터베이스처럼 예약 기능(pg_cron)이 없으면 건너뜀
do $$
begin
  if exists (select 1 from pg_extension where extname = 'pg_cron') then
    perform cron.schedule('hub-auto-grant-leave', '5 15 * * *',
      $c$select public.auto_grant_annual_leave((timezone('Asia/Seoul', now()))::date)$c$);
  end if;
end $$;

-- ---------------------------------------------------------------- 예전 대시보드 근태 옮기기 (대표·팀장)
-- 예전 직원 번호 → 통합 시스템 직원 (예전 번호가 연결된 직원 → 같은 이름 → 없으면 퇴사 직원으로 만듦)
-- 예전 번호(legacy_id)로 이미 옮긴 기록은 최신 상태로 고치고, 예전에서 지워진 기록은 여기서도 지움
create or replace function public.import_legacy_attendance(payload jsonb) returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  x jsonb; sid uuid; emap jsonb := '{}'; created text[] := '{}';
  n_leave int := 0; n_exc int := 0; n_rec int := 0; n_skip int := 0; n_corr int := 0; n_del int := 0;
begin
  if not public.is_manager() then raise exception '대표·팀장만 옮길 수 있습니다'; end if;
  perform set_config('app.att_import', 'on', true);

  -- 직원
  for x in select * from jsonb_array_elements(coalesce(payload->'employees', '[]')) loop
    select id into sid from public.staff where legacy_dashboard_employee_id = (x->>'id')::bigint;
    if sid is null then
      select id into sid from public.staff where name = trim(x->>'name') order by is_active desc limit 1;
      if sid is not null then
        update public.staff set legacy_dashboard_employee_id = (x->>'id')::bigint where id = sid and legacy_dashboard_employee_id is null;
      else
        insert into public.staff(name, role, is_active, legacy_dashboard_employee_id) values (trim(x->>'name'), 'staff', false, (x->>'id')::bigint)
        returning id into sid;
        created := created || trim(x->>'name');
      end if;
    end if;
    emap := emap || jsonb_build_object(x->>'id', sid);
    insert into public.staff_hr(staff_id, join_date, birthday_month, birthday_day, work_type, leave_grant_mode, work_phone)
    values (sid, (x->>'join_date')::date, (x->>'birthday_month')::int, (x->>'birthday_day')::int,
            coalesce(x->>'work_type', 'standard'), coalesce(x->>'leave_grant_mode', 'accounting_auto'), nullif(x->>'work_phone', ''))
    on conflict (staff_id) do update set join_date = excluded.join_date, birthday_month = excluded.birthday_month, birthday_day = excluded.birthday_day,
      work_type = excluded.work_type, leave_grant_mode = excluded.leave_grant_mode, work_phone = coalesce(excluded.work_phone, public.staff_hr.work_phone),
      updated_at = now();
  end loop;

  -- 근무 설정·공휴일
  update public.work_settings w set setting_value = s.value, updated_at = now()
    from jsonb_each_text(coalesce(payload->'settings', '{}')) s where w.setting_key = s.key and w.setting_value is distinct from s.value;
  insert into public.company_holidays(holiday_date, holiday_name)
  select (h->>'date')::date, h->>'name' from jsonb_array_elements(coalesce(payload->'holidays', '[]')) h
  on conflict (holiday_date) do update set holiday_name = excluded.holiday_name;

  -- 연차 부여·월차
  insert into public.leave_balances(staff_id, leave_year, granted_leave, adjustment_leave, note, created_at)
  select (emap->>(b->>'employee_id'))::uuid, (b->>'leave_year')::int, (b->>'granted_leave')::numeric, (b->>'adjustment_leave')::numeric,
         b->>'note', coalesce((b->>'created_at')::timestamptz, now())
    from jsonb_array_elements(coalesce(payload->'balances', '[]')) b where emap ? (b->>'employee_id')
  on conflict (staff_id, leave_year) do update set granted_leave = excluded.granted_leave, adjustment_leave = excluded.adjustment_leave, note = excluded.note;
  insert into public.leave_monthly_grants(staff_id, grant_date, granted_days, note, created_at)
  select (emap->>(g->>'employee_id'))::uuid, (g->>'grant_date')::date, (g->>'granted_days')::numeric, g->>'note', coalesce((g->>'created_at')::timestamptz, now())
    from jsonb_array_elements(coalesce(payload->'grants', '[]')) g where emap ? (g->>'employee_id')
  on conflict (staff_id, grant_date) do nothing;

  -- 휴가 신청
  for x in select * from jsonb_array_elements(coalesce(payload->'leaves', '[]')) loop
    continue when not emap ? (x->>'employee_id');
    insert into public.leave_requests(staff_id, leave_type, start_date, end_date, leave_days, deduct_leave, reason, status,
      approved_by, approved_at, cancel_status, cancel_reason, created_at, legacy_id)
    values ((emap->>(x->>'employee_id'))::uuid, x->>'leave_type', (x->>'start_date')::date, (x->>'end_date')::date, (x->>'leave_days')::numeric,
      (x->>'deduct_leave')::boolean, x->>'reason', x->>'status', (emap->>(x->>'approved_by'))::uuid, (x->>'approved_at')::timestamptz,
      x->>'cancel_status', x->>'cancel_reason', coalesce((x->>'created_at')::timestamptz, now()), (x->>'id')::bigint)
    on conflict (legacy_id) do update set leave_type = excluded.leave_type, start_date = excluded.start_date, end_date = excluded.end_date,
      leave_days = excluded.leave_days, deduct_leave = excluded.deduct_leave, reason = excluded.reason, status = excluded.status,
      approved_by = excluded.approved_by, approved_at = excluded.approved_at, cancel_status = excluded.cancel_status, cancel_reason = excluded.cancel_reason;
    n_leave := n_leave + 1;
  end loop;
  update public.leave_requests lr set resubmitted_from_id = p.id
    from jsonb_array_elements(coalesce(payload->'leaves', '[]')) j
    join public.leave_requests p on p.legacy_id = (j->>'resubmitted_from_id')::bigint
   where lr.legacy_id = (j->>'id')::bigint and lr.resubmitted_from_id is distinct from p.id;

  -- 근태 예외
  for x in select * from jsonb_array_elements(coalesce(payload->'exceptions', '[]')) loop
    continue when not emap ? (x->>'employee_id');
    insert into public.attendance_exceptions(staff_id, work_date, exception_type, start_time, end_time, return_to_office, approved_leave_time,
      location, note, status, approved_by, created_at, legacy_id)
    values ((emap->>(x->>'employee_id'))::uuid, (x->>'work_date')::date, x->>'exception_type', (x->>'start_time')::time, (x->>'end_time')::time,
      (x->>'return_to_office')::boolean, (x->>'approved_leave_time')::time, x->>'location', x->>'note', x->>'status',
      (emap->>(x->>'approved_by'))::uuid, coalesce((x->>'created_at')::timestamptz, now()), (x->>'id')::bigint)
    on conflict (legacy_id) do update set work_date = excluded.work_date, exception_type = excluded.exception_type, start_time = excluded.start_time,
      end_time = excluded.end_time, return_to_office = excluded.return_to_office, approved_leave_time = excluded.approved_leave_time,
      location = excluded.location, note = excluded.note, status = excluded.status, approved_by = excluded.approved_by;
    n_exc := n_exc + 1;
  end loop;

  -- 출퇴근 기록 (같은 날 통합 시스템에서 이미 출근한 기록이 있으면 그쪽을 남김)
  for x in select * from jsonb_array_elements(coalesce(payload->'records', '[]')) loop
    continue when not emap ? (x->>'employee_id');
    sid := (emap->>(x->>'employee_id'))::uuid;
    if exists (select 1 from public.attendance_records where staff_id = sid and work_date = (x->>'work_date')::date
                and legacy_id is distinct from (x->>'id')::bigint) then
      n_skip := n_skip + 1;
      continue;
    end if;
    insert into public.attendance_records(staff_id, work_date, clock_in, clock_out, attendance_status, is_late, is_early_leave, note,
      leave_request_id, attendance_exception_id, created_at, updated_at, legacy_id)
    values (sid, (x->>'work_date')::date, (x->>'clock_in')::timestamptz, (x->>'clock_out')::timestamptz, x->>'attendance_status',
      (x->>'is_late')::boolean, (x->>'is_early_leave')::boolean, x->>'note',
      (select id from public.leave_requests where legacy_id = (x->>'leave_request_id')::bigint),
      (select id from public.attendance_exceptions where legacy_id = (x->>'attendance_exception_id')::bigint),
      coalesce((x->>'created_at')::timestamptz, now()), coalesce((x->>'updated_at')::timestamptz, now()), (x->>'id')::bigint)
    on conflict (legacy_id) do update set clock_in = excluded.clock_in, clock_out = excluded.clock_out, attendance_status = excluded.attendance_status,
      is_late = excluded.is_late, is_early_leave = excluded.is_early_leave, note = excluded.note, leave_request_id = excluded.leave_request_id,
      attendance_exception_id = excluded.attendance_exception_id, updated_at = excluded.updated_at;
    n_rec := n_rec + 1;
  end loop;

  -- 예전에서 지워진 기록은 여기서도 지움 (예: 승인 취소된 휴가의 근태)
  with d as (
    delete from public.attendance_records r where r.legacy_id is not null
       and not exists (select 1 from jsonb_array_elements(coalesce(payload->'records', '[]')) j where (j->>'id')::bigint = r.legacy_id)
    returning 1)
  select count(*) into n_del from d;
  delete from public.attendance_exceptions e where e.legacy_id is not null
     and not exists (select 1 from jsonb_array_elements(coalesce(payload->'exceptions', '[]')) j where (j->>'id')::bigint = e.legacy_id);
  delete from public.leave_requests l where l.legacy_id is not null
     and not exists (select 1 from jsonb_array_elements(coalesce(payload->'leaves', '[]')) j where (j->>'id')::bigint = l.legacy_id);

  -- 근태 수정 요청·변경 이력
  for x in select * from jsonb_array_elements(coalesce(payload->'corrections', '[]')) loop
    continue when not emap ? (x->>'employee_id');
    continue when not exists (select 1 from public.attendance_records where legacy_id = (x->>'attendance_record_id')::bigint);
    insert into public.attendance_correction_requests(attendance_record_id, staff_id, work_date, requested_clock_in, requested_clock_out, reason,
      status, processed_by, processed_at, process_note, created_at, legacy_id)
    values ((select id from public.attendance_records where legacy_id = (x->>'attendance_record_id')::bigint), (emap->>(x->>'employee_id'))::uuid,
      (x->>'work_date')::date, (x->>'requested_clock_in')::timestamptz, (x->>'requested_clock_out')::timestamptz, x->>'reason', x->>'status',
      (emap->>(x->>'processed_by'))::uuid, (x->>'processed_at')::timestamptz, x->>'process_note', coalesce((x->>'created_at')::timestamptz, now()), (x->>'id')::bigint)
    on conflict (legacy_id) do update set status = excluded.status, processed_by = excluded.processed_by, processed_at = excluded.processed_at,
      process_note = excluded.process_note;
    n_corr := n_corr + 1;
  end loop;
  insert into public.attendance_record_history(attendance_record_id, staff_id, work_date, old_clock_in, new_clock_in, old_clock_out, new_clock_out,
    old_attendance_status, new_attendance_status, old_is_late, new_is_late, old_is_early_leave, new_is_early_leave, old_note, new_note,
    change_reason, changed_by, created_at, legacy_id)
  select r.id, r.staff_id, (h->>'work_date')::date, (h->>'old_clock_in')::timestamptz, (h->>'new_clock_in')::timestamptz,
         (h->>'old_clock_out')::timestamptz, (h->>'new_clock_out')::timestamptz, h->>'old_attendance_status', h->>'new_attendance_status',
         (h->>'old_is_late')::boolean, (h->>'new_is_late')::boolean, (h->>'old_is_early_leave')::boolean, (h->>'new_is_early_leave')::boolean,
         h->>'old_note', h->>'new_note', h->>'change_reason', (emap->>(h->>'changed_by'))::uuid, coalesce((h->>'created_at')::timestamptz, now()), (h->>'id')::bigint
    from jsonb_array_elements(coalesce(payload->'record_history', '[]')) h
    join public.attendance_records r on r.legacy_id = (h->>'attendance_record_id')::bigint
  on conflict (legacy_id) do nothing;
  insert into public.leave_balance_history(staff_id, leave_year, old_granted_leave, new_granted_leave, old_adjustment_leave, new_adjustment_leave,
    change_note, changed_by, created_at, legacy_id)
  select (emap->>(h->>'employee_id'))::uuid, (h->>'leave_year')::int, (h->>'old_granted_leave')::numeric, (h->>'new_granted_leave')::numeric,
         (h->>'old_adjustment_leave')::numeric, (h->>'new_adjustment_leave')::numeric, h->>'change_note', (emap->>(h->>'changed_by'))::uuid,
         coalesce((h->>'created_at')::timestamptz, now()), (h->>'id')::bigint
    from jsonb_array_elements(coalesce(payload->'balance_history', '[]')) h where emap ? (h->>'employee_id')
  on conflict (legacy_id) do nothing;

  perform set_config('app.att_import', '', true);
  return jsonb_build_object('leaves', n_leave, 'exceptions', n_exc, 'records', n_rec, 'skipped_records', n_skip, 'removed_records', n_del,
                            'corrections', n_corr, 'created_staff', to_jsonb(created));
end
$$;

-- ---------------------------------------------------------------- 보안 규칙
alter table public.staff_hr enable row level security;
alter table public.work_settings enable row level security;
alter table public.work_setting_history enable row level security;
alter table public.company_holidays enable row level security;
alter table public.leave_balances enable row level security;
alter table public.leave_balance_history enable row level security;
alter table public.leave_monthly_grants enable row level security;
alter table public.leave_requests enable row level security;
alter table public.attendance_exceptions enable row level security;
alter table public.attendance_records enable row level security;
alter table public.attendance_record_history enable row level security;
alter table public.attendance_correction_requests enable row level security;

-- 인사 정보: 본인과 대표·팀장이 보고, 대표·팀장이 고침
create policy staff_hr_select on public.staff_hr for select to authenticated using (staff_id = public.my_staff_id() or public.is_manager());
create policy staff_hr_insert on public.staff_hr for insert to authenticated with check (public.is_manager());
create policy staff_hr_update on public.staff_hr for update to authenticated using (public.is_manager()) with check (public.is_manager());

-- 근무 설정·공휴일: 모두 보고, 공휴일은 대표·팀장이 넣고 지움 (설정은 work_setting_set으로만)
create policy work_settings_select on public.work_settings for select to authenticated using (public.my_staff_id() is not null);
create policy company_holidays_select on public.company_holidays for select to authenticated using (public.my_staff_id() is not null);
create policy company_holidays_insert on public.company_holidays for insert to authenticated with check (public.is_manager());
create policy company_holidays_update on public.company_holidays for update to authenticated using (public.is_manager()) with check (public.is_manager());
create policy company_holidays_delete on public.company_holidays for delete to authenticated using (public.is_manager());

-- 본인 것 + 대표·팀장은 전체 (고치는 건 위 함수로만)
create policy leave_balances_select on public.leave_balances for select to authenticated using (staff_id = public.my_staff_id() or public.is_manager());
create policy leave_monthly_grants_select on public.leave_monthly_grants for select to authenticated using (staff_id = public.my_staff_id() or public.is_manager());
create policy leave_requests_select on public.leave_requests for select to authenticated using (staff_id = public.my_staff_id() or public.is_manager());
create policy attendance_exceptions_select on public.attendance_exceptions for select to authenticated using (staff_id = public.my_staff_id() or public.is_manager());
create policy attendance_records_select on public.attendance_records for select to authenticated using (staff_id = public.my_staff_id() or public.is_manager());
create policy attendance_corrections_select on public.attendance_correction_requests for select to authenticated using (staff_id = public.my_staff_id() or public.is_manager());
create policy leave_balance_history_select on public.leave_balance_history for select to authenticated using (public.is_manager());
create policy attendance_record_history_select on public.attendance_record_history for select to authenticated using (public.is_manager());
create policy work_setting_history_select on public.work_setting_history for select to authenticated using (public.is_manager());

-- 신청은 본인이 직접(결재 전 상태로만). 대표·팀장은 다른 직원 것도 대신 넣을 수 있음
create policy leave_requests_insert on public.leave_requests for insert to authenticated
  with check ((staff_id = public.my_staff_id() or public.is_manager()) and status = 'pending'
              and first_approved_by is null and approved_by is null and cancel_status is null and legacy_id is null);
create policy attendance_exceptions_insert on public.attendance_exceptions for insert to authenticated
  with check (legacy_id is null and ((staff_id = public.my_staff_id() and status = 'pending') or public.is_manager()));

revoke all on public.staff_hr, public.work_settings, public.work_setting_history, public.company_holidays, public.leave_balances,
  public.leave_balance_history, public.leave_monthly_grants, public.leave_requests, public.attendance_exceptions, public.attendance_records,
  public.attendance_record_history, public.attendance_correction_requests from anon;

revoke execute on function public.leave_requests_before(), public.leave_requests_sync_attendance(), public.attendance_exceptions_before(),
  public.attendance_exceptions_sync(), public.attendance_records_before() from public, anon, authenticated;
revoke execute on function public.clock_in(uuid), public.clock_out(uuid), public.leave_decide(bigint, text, boolean, text),
  public.leave_withdraw(bigint), public.leave_cancel_request(bigint, text), public.leave_cancel_decide(bigint, text),
  public.attendance_exception_decide(bigint, text), public.attendance_record_save(uuid, date, timestamptz, timestamptz, text, text),
  public.attendance_correction_request(bigint, timestamptz, timestamptz, text), public.attendance_correction_decide(bigint, text, text),
  public.leave_balance_set(uuid, int, numeric, numeric, text), public.leave_summary(int), public.work_setting_set(text, text),
  public.att_calendar(date, date), public.import_legacy_attendance(jsonb), public.att_evaluate(uuid, date, timestamptz, timestamptz),
  public.att_check_self(uuid), public.att_setting(text), public.att_work_type(uuid) from public, anon;
grant execute on function public.clock_in(uuid), public.clock_out(uuid), public.leave_decide(bigint, text, boolean, text),
  public.leave_withdraw(bigint), public.leave_cancel_request(bigint, text), public.leave_cancel_decide(bigint, text),
  public.attendance_exception_decide(bigint, text), public.attendance_record_save(uuid, date, timestamptz, timestamptz, text, text),
  public.attendance_correction_request(bigint, timestamptz, timestamptz, text), public.attendance_correction_decide(bigint, text, text),
  public.leave_balance_set(uuid, int, numeric, numeric, text), public.leave_summary(int), public.work_setting_set(text, text),
  public.att_calendar(date, date), public.import_legacy_attendance(jsonb) to authenticated;
revoke execute on function public.att_evaluate(uuid, date, timestamptz, timestamptz), public.att_check_self(uuid) from authenticated;
